In [64]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [71]:
colonne = ["Data", "Ora", "Id_rete_monit", "Codice_istat_comune", "Progr_punto_com",
           "Velv", "Dirv", "Devst", "Baro", "Terma", "Igro", "Radd", "Radr", "Pluv"]

data = pd.read_csv("./Month.csv", names=colonne, header=None, na_values=9999.9)
data["Ora"] = pd.to_datetime(data["Ora"], format="%H:%M").dt.hour
data["Mese"] = pd.to_datetime(data["Data"], format="%d-%m-%Y").dt.month
data

,Data,Ora,Id_rete_monit,Codice_istat_comune,Progr_punto_com,Velv,Dirv,Devst,Baro,Terma,Igro,Radd,Radr,Pluv,Mese
0,01-01-2010,0,17,4028,900,0.4,175.7,NaN,925.7,1.3,84.0,NaN,NaN,0.0,1
1,01-01-2010,1,17,4028,900,0.0,NaN,NaN,925.1,1.3,84.0,NaN,NaN,0.0,1
2,01-01-2010,2,17,4028,900,0.6,197.0,NaN,924.6,1.4,84.0,NaN,NaN,0.0,1
3,01-01-2010,3,17,4028,900,0.9,187.1,NaN,923.8,1.7,84.0,NaN,NaN,0.0,1
4,01-01-2010,4,17,4028,900,1.1,190.7,NaN,923.4,2.2,82.0,NaN,NaN,0.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8755,31-12-2010,19,17,4028,900,1.0,177.2,NaN,952.6,-3.5,99.0,NaN,NaN,0.0,12
8756,31-12-2010,20,17,4028,900,1.3,190.5,NaN,952.3,-3.7,100.0,NaN,NaN,0.0,12
8757,31-12-2010,21,17,4028,900,1.3,182.1,NaN,952.8,-3.9,100.0,NaN,NaN,0.0,12
8758,31-12-2010,22,17,4028,900,1.3,186.4,NaN,953.0,-4.5,100.0,NaN,NaN,0.0,12
8759,31-12-2010,23,17,4028,900,1.8,182.5,NaN,952.9,-4.5,100.0,NaN,NaN,0.0,12

In [66]:
features = ["Velv", "Baro", "Igro", "Pluv", "Dirv", "Ora", "Mese"]
target = ["Terma"]
useful_data = data[features + target]
useful_data.dropna(inplace=True)
useful_data

C:\Users\Paolo\AppData\Local\Temp\ipykernel_8400\3543406453.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  useful_data.dropna(inplace=True)

      Velv   Baro   Igro  Pluv   Dirv  Ora  Mese  Terma
0      0.4  925.7   84.0   0.0  175.7    0     1    1.3
2      0.6  924.6   84.0   0.0  197.0    2     1    1.4
3      0.9  923.8   84.0   0.0  187.1    3     1    1.7
4      1.1  923.4   82.0   0.0  190.7    4     1    2.2
5      1.1  923.2   80.0   0.0  211.9    5     1    2.5
...    ...    ...    ...   ...    ...  ...   ...    ...
8755   1.0  952.6   99.0   0.0  177.2   19    12   -3.5
8756   1.3  952.3  100.0   0.0  190.5   20    12   -3.7
8757   1.3  952.8  100.0   0.0  182.1   21    12   -3.9
8758   1.3  953.0  100.0   0.0  186.4   22    12   -4.5
8759   1.8  952.9  100.0   0.0  182.5   23    12   -4.5

[6682 rows x 8 columns]

In [67]:
model = LinearRegression()

In [68]:
X = useful_data[features].to_numpy()
y = useful_data[target].to_numpy()

In [69]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42)

In [70]:
model.fit(X_train, y_train)
model.score(X_test, y_test)

0.2646760984655141